name: Execute build

on:
  workflow_call:
    inputs:
      checkout_branch:
        description: 'Branch to checkout before building'
        required: true
        type: string

jobs:
  execute-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.checkout_branch }}

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Build Release
        run: ./gradlew assembleRelease
