name: Version Catalog Update

on:
    workflow_dispatch:

jobs:
    version-catalog-update:
        runs-on: ubuntu-latest
        outputs:
            version_catalog_output: ${{ steps.version_catalog_update.outputs.result }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                  distribution: 'adopt'
                  java-version: '11'

            - name: Cache Gradle packages
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.gradle/caches
                      ~/.gradle/wrapper
                  key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                  restore-keys: |
                      gradle-${{ runner.os }}-

            - name: Set up Android SDK
              uses: android-actions/setup-android@v2
              with:
                  api-levels: 33
                  build-tools: 33.0.2
                  components: build-tools;33.0.2

            - name: Grant execute permission for gradlew
              run: chmod +x ./gradlew

            - name: Run versionCatalogUpdate
              id: version_catalog_update
              run: |
                  ./gradlew versionCatalogUpdate
                  echo "::set-output name=result::success"

    tests-and-build:
        needs: version-catalog-update
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                  distribution: 'adopt'
                  java-version: '11'

            - name: Cache Gradle packages
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.gradle/caches
                      ~/.gradle/wrapper
                  key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                  restore-keys: |
                      gradle-${{ runner.os }}-

            - name: Set up Android SDK
              uses: android-actions/setup-android@v2
              with:
                  api-levels: 33
                  build-tools: 33.0.2
                  components: build-tools;33.0.2

            - name: Grant execute permission for gradlew
              run: chmod +x ./gradlew

            - name: Run Unit Tests
              run: ./gradlew test

            - name: Build Release
              run: ./gradlew assembleRelease

    create-pr:
        needs: tests-and-build
        runs-on: ubuntu-latest
        if: needs.tests-and-build.result == 'success'
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Configure git
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'

            - name: Create a new branch
              run: |
                  git checkout -b update-version-catalog
                  git add .
                  git commit -m "Update version catalog"

            - name: Push changes
              run: |
                  git push --set-upstream origin update-version-catalog

            - name: Create Pull Request
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  gh pr create --title "Update version catalog" --body "Automated update of version catalog" --base develop --head update-version-catalog
