name: Version Catalog Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 3"

jobs:
  version-catalog-update:
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.check_changes.outputs.has_changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Run versionCatalogUpdate
        id: version_catalog_update
        run: ./gradlew versionCatalogUpdate

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "No changes detected"
            echo "::set-output name=has_changes::false"
          else
            echo "Changes detected"
            echo "::set-output name=has_changes::true"
          fi

  tests:
    if: needs.version-catalog-update.outputs.has_changes == 'true'
    needs: version-catalog-update
    uses: ./.github/workflows/execute-tests.yml
    with:
      checkout_branch: 'develop'

  build:
    if: needs.version-catalog-update.outputs.has_changes == 'true'
    needs: version-catalog-update
    uses: ./.github/workflows/execute-build.yml
    with:
      checkout_branch: 'develop'

  create-pr:
    if: success()
    needs:
      - tests
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Run versionCatalogUpdate
        id: version_catalog_update
        run: ./gradlew versionCatalogUpdate

      - name: Create a new branch
        run: |
          git checkout -b update-version-catalog
          git add .
          git commit -m "Update version catalog"

      - name: Push changes
        run: |
          git push --set-upstream origin update-version-catalog

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "Update version catalog" --body "Automated update of version catalog" --base develop --head update-version-catalog
